all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become: yes
    ansible_become_method: sudo 
  children:
    vultr:
      hosts:
        host.example.com:
          user: user
          user_passwd: "{{ host_user_passwd }}"
          root_passwd: "{{ host_root_passwd }}"
          ssh_pub_key: "{{ lookup('file', '~/.ssh/host_ed25519.pub')  }}"
          ansible_become_pass: "{{ host_user_passwd }}"
          cfg_static_network: false
    # vmware:
    #   hosts:
    #     debian1.local:
    #       user: george
    #       user_passwd: "{{ db1_user_passwd }}"
    #       root_passwd: "{{ db1_root_passwd }}"
    #       ssh_pub_key: "{{ lookup('file', '~/.ssh/db1_ed25519.pub')  }}"
    #       ansible_become_pass: "{{ db1_user_passwd }}"
    #       cfg_static_network: true